workfile修正

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -62,8 +62,8 @@ jobs:
 #      run: make download-firebase-sdk
 
     # ライセンス情報の生成
-    - name: Generate licenses
-      run: make generate-licenses
+#    - name: Generate licenses
+#      run: make generate-licenses
 
     # プロジェクトファイルの生成
     - name: Generate Xcode project for develop
@@ -129,8 +129,8 @@ jobs:
 #      run: make download-firebase-sdk
 
     # ライセンス情報の生成
-    - name: Generate licenses
-      run: make generate-licenses
+#    - name: Generate licenses
+#      run: make generate-licenses
 
     # プロジェクトファイルの生成
     - name: Generate Xcode project for develop
@@ -149,10 +149,10 @@ jobs:
       run: make test
 
     # 結果の表示
-    - uses: kishikawakatsumi/xcresulttool@v1
-      if: success() || failure()
-      with:
-        path: TestResults.xcresult
+#    - uses: kishikawakatsumi/xcresulttool@v1
+#      if: success() || failure()
+#      with:
+#        path: TestResults.xcresult
 
     # 単体テストログのアップロード
     - name: Upload test log Artifact
